// <auto-generated />
namespace Week2Oefening1.BusinessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dlklkdslksd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dlklkdslksd));
        
        string IMigrationMetadata.Id
        {
            get { return "201504211503405_dlklkdslksd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
