// <auto-generated />
namespace Webshop.BusinessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitDb270415 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDb270415));
        
        string IMigrationMetadata.Id
        {
            get { return "201504271945108_InitDb270415"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
